name: Divorce Care
favicon: null
layout_spectrum: 0.4107099180109799
typography_spectrum: 0.030478671891614795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.519578913692385
  lightness: 0.9821756926830858
  saturation: 0.532370877219364
  rhythmicContrast: 0.7911719682160765
purpose: []
